#ifndef __HLIB_PARSER_TYPING_ENUM
#define __HLIB_PARSER_TYPING_ENUM

typedef enum
{
  PARSER_PIPELINE_STATUS_PASS,
  PARSER_PIPELINE_STATUS_HOLD,
  PARSER_PIPELINE_STATUS_CATCH,
  PARSER_PIPELINE_STATUS_RESET,
  PARSER_PIPELINE_STATUS_FLUSH,
  PARSER_PIPELINE_STATUS_ENDL,
  PARSER_PIPELINE_STATUS_EXIT,
} PARSER_PIPELINE_STATUS;

#endif /* __HLIB_PARSER_TYPING_ENUM */
