#ifndef __HLIB_UTILS_SYMBOLS
#define __HLIB_UTILS_SYMBOLS

const void *ENDARG = (void *)&"WELLKNOWN_SYMBOL_ENDARG";
const void *DEFAULTARG = (void *)&"WELLKNOWN_SYMBOL_DEFAULTARG";

#endif /* __HLIB_UTILS_SYMBOLS */
